  server:
    port: 8081
  rocketmq:
    name-server: 192.168.10.102:9876 # 换成你虚拟机的IP
    producer:
      group: hmdp-group
  spring:
    application:
      name: hmdp
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/hmdp?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
      username: root
      password: 123456
    redis:
      host: 192.168.10.102
      port: 6379

      lettuce:
        pool:
          max-active: 30
          max-idle: 15
          min-idle: 5
          time-between-eviction-runs: 10s
      password: 123456
    jackson:
      default-property-inclusion: non_null # JSON处理时忽略非空字段
  mybatis-plus:
    type-aliases-package: com.hmdp.entity # 别名扫描包
  logging:
    level:
      com.hmdp: debug
